# GAME SETTINGS
WIN_WIDTH = 500
WIN_HEIGHT = 500

TILE_SIZE = 25

GRID_TILES_X = WIN_WIDTH // TILE_SIZE
GRID_TILES_Y = WIN_HEIGHT // TILE_SIZE

FPS = 8

# COLORS
LIGHT_GRAY = (150, 150, 150)
BLACK = (0, 0, 0)
GREEN = (0, 255, 0)
RED = (255, 0, 0)


# SNAKE CONSTANTS
STARTING_SIZE = 1
STARTING_POS = (WIN_WIDTH // (2 * TILE_SIZE), WIN_HEIGHT // (2 * TILE_SIZE))

DIR_UP = 1
DIR_RIGHT = 2
DIR_DOWN = -1
DIR_LEFT = -2

# BOARD FLAGS
EMPTY = 0
TARGET = 1
SNAKE = -1
